config/routes.rb
Rails.application.routes.draw do  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "chat#index"
  get "login", to: "login#index"
  post "login", to: "login#login"
  delete "logout", to: "login#logout"
  post "message", to: "messages#create"

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true

  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You need to be logged in"
      redirect_to login_path
    end
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  before_action :require_user, only: [:index]

  def index
    @message = Message.new
    @messages = Message.custom_display #Message.all
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :require_not_logged_in, only: [:index, :login]
  before_action :require_user, only: [:logout]
  
  def index
  end

  def login
    user = User.find_by(username: params[:login][:username].downcase)
    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully"
      redirect_to root_path
    else
      flash.now[:error] = "Invalid login credentials"
      render "index"
    end
  end

  def logout
    session[:user_id] = nil
    flash[:success] = "You're logged out"
    redirect_to login_path
  end

  private

  def require_not_logged_in
    if logged_in?
      flash[:error] = "You're already logged in"
      redirect_to root_path
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      #redirect_to root_path
      ActionCable.server.broadcast "chat_channel", message: render_message(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def render_message(message)
    render(partial: "message", locals: { message: message })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="circular comments icon red"></i>
  Chat
</h2>
<div class='ui grid'>
  <div class='four wide column'>
    <div class="ui inverted vertical pointing menu">
      <a class="active item">
        Home
      </a>
      <a class="item">
        Messages
      </a>
      <a class="item">
        Friends
      </a>
    </div>
  </div>
  <div class='twelve wide column'>
    <div class='ui fluid raised card chatbox'>
      <div class='content'>
        <div class="ui feed" id="chat-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: 'ui reply form'}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: 'Enter a message...' %>
              <%= f.button '<i class="red arrow alternate bordered inverted right large icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, content| %>
  <div class="ui <%= type %> message">
    <i class="close icon"></i>
    <div class='header'><%= content %></div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui inverted small menu">
  <div class='ui container'>
    <%= link_to "Chat", root_path, class: "active item"%>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to "Logout", logout_path, class: 'item', method: :delete %>
          <% else %>
            <%= link_to "Login", login_path, class: "item"%>
            <a class="item">Sign Up</a>
          <% end %>
        </div>
      </div>
      <% if !logged_in? %>
        <div class="item">
          <div class="ui primary button">Sign Up</div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admconnect</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class='ui container'>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/login/index.html.erb
<h1 class='ui center aligned header'>Welcome to ADM Connect</h1>
<h2 class="ui center aligned medium icon header">
  <i class="circular power icon red"></i>
  Login to continue
</h2>
<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <%= form_for(:login, html: {class:"ui form"}, url: login_path) do |f| %>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Password"%>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "Login", class: "ui red submit button"%>
      <% end %>
    </div>
    <div class="middle aligned column">
      <div class="ui big button">
        <i class="signup icon"></i>
        Sign Up
      </div>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>